//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bet.Bussiness.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bet.Bussiness.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email đã tồn tại.
        /// </summary>
        internal static string ErrorService_Employee_Email_duplicate {
            get {
                return ResourceManager.GetString("ErrorService_Employee_Email_duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khách hàng đã tồn tại.
        /// </summary>
        internal static string ErrorService_Employee_EmployeeCode_duplicate {
            get {
                return ResourceManager.GetString("ErrorService_Employee_EmployeeCode_duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại đã tồn tại.
        /// </summary>
        internal static string ErrorService_Employee_PhoneNumber_duplicate {
            get {
                return ResourceManager.GetString("ErrorService_Employee_PhoneNumber_duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không được bỏ trống.
        /// </summary>
        internal static string ErrorService_Required {
            get {
                return ResourceManager.GetString("ErrorService_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa nhân viên.
        /// </summary>
        internal static string ErrorServive_Employee_Delete {
            get {
                return ResourceManager.GetString("ErrorServive_Employee_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id nhân viên không tồn tại.
        /// </summary>
        internal static string ErrorServive_Employee_EmployeeId_notExist {
            get {
                return ResourceManager.GetString("ErrorServive_Employee_EmployeeId_notExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể lấy thông tin danh sách nhân viên.
        /// </summary>
        internal static string ErrorServive_Employee_GetData {
            get {
                return ResourceManager.GetString("ErrorServive_Employee_GetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể thêm mới nhân viên.
        /// </summary>
        internal static string ErrorServive_Employee_Insert {
            get {
                return ResourceManager.GetString("ErrorServive_Employee_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể cập nhật nhân viên.
        /// </summary>
        internal static string ErrorServive_Employee_Update {
            get {
                return ResourceManager.GetString("ErrorServive_Employee_Update", resourceCulture);
            }
        }
    }
}
