--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.338.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 9/24/2023 5:58:04 PM
-- Server version: 8.0.32
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS betdata;

CREATE DATABASE betdata
CHARACTER SET utf8mb4
COLLATE utf8mb4_0900_ai_ci;

--
-- Set default database
--
USE betdata;

--
-- Create table `user`
--
CREATE TABLE user (
  Id int NOT NULL AUTO_INCREMENT,
  FullName varchar(60) DEFAULT NULL COMMENT 'Tên đầy đủ',
  FirstName varchar(30) DEFAULT NULL COMMENT 'Họ đệm',
  LastName varchar(30) DEFAULT NULL COMMENT 'Tên',
  UserName varchar(30) DEFAULT NULL COMMENT 'Tên đăng nhập',
  Password varchar(30) DEFAULT NULL COMMENT 'Mật khẩu',
  PasswordMd5 varchar(400) DEFAULT NULL COMMENT 'Mật khẩu MD5',
  Phone varchar(12) DEFAULT NULL COMMENT 'Số điện thoại',
  Email varchar(200) DEFAULT NULL COMMENT 'Email',
  BankType int DEFAULT NULL COMMENT 'Loại ngân hàng',
  TypeName varchar(30) DEFAULT NULL COMMENT 'Tên ngân hàng',
  BankNumber varchar(16) DEFAULT NULL COMMENT 'Số tài khoản',
  BankName varchar(60) DEFAULT NULL COMMENT 'Tên tài khoản ngân hàng',
  Money float(10, 2) DEFAULT NULL COMMENT 'Số tiền hiện có',
  CreatedDate datetime DEFAULT NULL COMMENT 'Ngày tạo',
  CreatedId int DEFAULT NULL COMMENT 'Người tạo',
  CreatedName varchar(60) DEFAULT NULL COMMENT 'Tên người tạo',
  ModifiedDate datetime DEFAULT NULL COMMENT 'Ngày sửa',
  ModifiedId int DEFAULT NULL COMMENT 'Người sửa',
  ModifiedName varchar(60) DEFAULT NULL COMMENT 'Tên người sửa',
  IsActive bit(1) DEFAULT NULL COMMENT 'Đã kích hoạt',
  IsDelete bit(1) DEFAULT NULL COMMENT 'Đã xóa',
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `tournament`
--
CREATE TABLE tournament (
  Id int NOT NULL AUTO_INCREMENT,
  Name varchar(4000) NOT NULL DEFAULT '' COMMENT 'Tên giải đấu',
  CreatedDate datetime DEFAULT NULL COMMENT 'Ngày tạo',
  CreatedId int DEFAULT NULL COMMENT 'Người tạo',
  CreatedName varchar(60) DEFAULT NULL COMMENT 'Tên đầy đủ',
  ModifiedDate datetime DEFAULT NULL COMMENT 'Ngày sửa',
  ModifiedId int DEFAULT NULL COMMENT 'Người sửa',
  ModifiedName varchar(60) DEFAULT NULL COMMENT 'Tên người sửa',
  IsDelete bit(1) DEFAULT NULL COMMENT 'Đã xóa',
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `team`
--
CREATE TABLE team (
  Id int NOT NULL AUTO_INCREMENT,
  Name varchar(200) NOT NULL DEFAULT '' COMMENT 'Tên đội bóng',
  CreatedDate datetime DEFAULT NULL COMMENT 'Ngày tạo',
  CreatedId int DEFAULT NULL COMMENT 'Người tạo',
  CreatedName varchar(60) DEFAULT NULL COMMENT 'Tên người tạo',
  ModifiedDate datetime DEFAULT NULL COMMENT 'Ngày sửa',
  ModifiedId int DEFAULT NULL COMMENT 'Người sửa',
  ModifiedName varchar(60) DEFAULT NULL COMMENT 'Tên người sửa',
  IsDelete bit(1) DEFAULT NULL COMMENT 'Đã xóa',
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `sicbo_real_time`
--
CREATE TABLE sicbo_real_time (
  Id int NOT NULL AUTO_INCREMENT,
  BetRealTimeId int DEFAULT NULL COMMENT 'bảng cá độ thười gian thực',
  Timeline tinyint DEFAULT NULL COMMENT 'thời gian trên sân',
  AboveId int DEFAULT NULL COMMENT 'idkèo trên',
  AboveName varchar(200) DEFAULT NULL COMMENT 'kèo trên',
  BelowId int DEFAULT NULL COMMENT 'kèo dưới',
  BelowName varchar(200) DEFAULT NULL COMMENT 'Tên kèo dưới',
  Type float(4, 2) DEFAULT NULL COMMENT 'loại kèo',
  TypeName varchar(16) DEFAULT NULL COMMENT 'Tên loại kèo',
  IsAbove bit(1) DEFAULT b'0' COMMENT 'Là tài hay xỉu 1: tài, 0 xỉu',
  Ratio float(4, 2) DEFAULT NULL COMMENT 'Tỷ số ăn',
  CreatedDate datetime DEFAULT NULL COMMENT 'Ngày tạo',
  CreatedId int DEFAULT NULL COMMENT 'Người tạo',
  CreatedName varchar(60) DEFAULT NULL COMMENT 'Tên người tạo',
  ModifiedDate datetime DEFAULT NULL COMMENT 'Ngày sửa',
  ModifiedId int DEFAULT NULL COMMENT 'Người sửa',
  ModifiedName varchar(60) DEFAULT NULL COMMENT 'Tên người sửa',
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `sicbo`
--
CREATE TABLE sicbo (
  Id int NOT NULL AUTO_INCREMENT,
  MatchTimeLineId int DEFAULT NULL COMMENT 'bảng cá độ',
  Type float(4, 2) DEFAULT NULL COMMENT 'loại kèo',
  TypeName varchar(16) DEFAULT NULL COMMENT 'Tên loại kèo',
  IsAbove bit(1) DEFAULT b'0' COMMENT 'Là tài hay xỉu 1: tài, 0 xỉu',
  Ratio float(4, 2) DEFAULT NULL COMMENT 'Tỷ số ăn',
  IsWin bit(1) DEFAULT NULL COMMENT 'Theo thời điểm này có thắng',
  CreatedDate datetime DEFAULT NULL COMMENT 'Ngày tạo',
  CreatedId int DEFAULT NULL COMMENT 'Người tạo',
  CreatedName varchar(60) DEFAULT NULL COMMENT 'Tên người tạo',
  ModifiedDate datetime DEFAULT NULL COMMENT 'Ngày sửa',
  ModifiedId int DEFAULT NULL COMMENT 'Người sửa',
  ModifiedName varchar(60) DEFAULT NULL COMMENT 'Tên người sửa',
  IsDelete bit(1) DEFAULT NULL COMMENT 'Đã xóa',
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `season`
--
CREATE TABLE season (
  Id int NOT NULL AUTO_INCREMENT,
  Name varchar(400) NOT NULL DEFAULT '' COMMENT 'Tên mùa giải',
  TotalRound int NOT NULL DEFAULT 0 COMMENT 'Tổng số vòng đấu',
  TournamentId int DEFAULT NULL,
  CreatedDate datetime DEFAULT NULL COMMENT 'Ngày tạo',
  CreatedId int DEFAULT NULL COMMENT 'Người tạo',
  CreatedName varchar(60) DEFAULT NULL COMMENT 'Tên đầy đủ',
  ModifiedDate datetime DEFAULT NULL COMMENT 'Ngày sửa',
  ModifiedId int DEFAULT NULL COMMENT 'Người sửa',
  ModifiedName varchar(60) DEFAULT NULL COMMENT 'Tên người sửa',
  IsDelete bit(1) DEFAULT NULL COMMENT 'Đã xóa',
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `role_user`
--
CREATE TABLE role_user (
  Id int NOT NULL AUTO_INCREMENT,
  UserId int DEFAULT NULL COMMENT 'Người dùng',
  RoleId int DEFAULT NULL COMMENT 'Vai trò',
  CreatedDate datetime DEFAULT NULL COMMENT 'Ngày tạo',
  CreatedId int DEFAULT NULL COMMENT 'Người tạo',
  CreatedName varchar(60) DEFAULT NULL COMMENT 'Tên người tạo',
  ModifiedDate datetime DEFAULT NULL COMMENT 'Ngày sửa',
  ModifiedId int DEFAULT NULL COMMENT 'Người sửa',
  ModifiedName varchar(60) DEFAULT NULL COMMENT 'Tên người sửa',
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `role`
--
CREATE TABLE role (
  Id int NOT NULL AUTO_INCREMENT,
  Name varchar(30) DEFAULT NULL COMMENT 'Tên vai trò',
  CreatedDate datetime DEFAULT NULL COMMENT 'Ngày tạo',
  CreatedId int DEFAULT NULL COMMENT 'Người tạo',
  CreatedName varchar(60) DEFAULT NULL COMMENT 'Tên người tạo',
  ModifiedDate datetime DEFAULT NULL COMMENT 'Ngày sửa',
  ModifiedId int DEFAULT NULL COMMENT 'Người sửa',
  ModifiedName varchar(60) DEFAULT NULL COMMENT 'Tên người sửa',
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `reference`
--
CREATE TABLE reference (
  Id int NOT NULL AUTO_INCREMENT,
  ForeignTable varchar(30) DEFAULT NULL COMMENT 'Bảng giá trị cần mapping',
  ReferenceTable varchar(30) DEFAULT NULL COMMENT 'Bảng giá trị nguồn',
  ForeignField varchar(30) DEFAULT NULL COMMENT 'Tên cột cần mapping',
  ReferenceField varchar(30) DEFAULT NULL COMMENT 'Tên cột có giá trị mapping',
  KeyCondition varchar(30) DEFAULT NULL COMMENT 'Điều kiện để lấy trường đích id = KeyCondition',
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `permission`
--
CREATE TABLE permission (
  Id int NOT NULL AUTO_INCREMENT,
  RoleId int DEFAULT NULL COMMENT 'Tên vai trò',
  LayoutCode varchar(30) DEFAULT NULL COMMENT 'Tên module',
  per int DEFAULT NULL COMMENT 'Quyền',
  CreatedDate datetime DEFAULT NULL COMMENT 'Ngày tạo',
  CreatedId int DEFAULT NULL COMMENT 'Người tạo',
  CreatedName varchar(60) DEFAULT NULL COMMENT 'Tên người tạo',
  ModifiedDate datetime DEFAULT NULL COMMENT 'Ngày sửa',
  ModifiedId int DEFAULT NULL COMMENT 'Người sửa',
  ModifiedName varchar(60) DEFAULT NULL COMMENT 'Tên người sửa',
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `match_time_line`
--
CREATE TABLE match_time_line (
  Id int NOT NULL AUTO_INCREMENT,
  TimeReal tinyint DEFAULT NULL COMMENT 'thời gian trên sân',
  MatchId int DEFAULT NULL COMMENT 'fk: thuộc trận đấu',
  AboveId int DEFAULT NULL COMMENT 'idkèo trên',
  AboveName varchar(200) DEFAULT NULL COMMENT 'Tên kèo trên',
  BelowId int DEFAULT NULL COMMENT 'Kèo dưới',
  BelowName varchar(200) DEFAULT NULL COMMENT 'Tên kèo dưới',
  IsAboveHost bit(1) DEFAULT NULL COMMENT 'kèo trên là chủ nhà',
  AboveScore tinyint DEFAULT NULL COMMENT 'Tỷ số kèo trên',
  BelowScore tinyint DEFAULT NULL COMMENT 'Tỷ số kèo dưới',
  AboveCorner tinyint DEFAULT NULL COMMENT 'Số phạt góc kèo trên',
  BelowCorner tinyint DEFAULT NULL COMMENT 'Số phạt góc kèo dưới',
  AbovePenalty tinyint DEFAULT NULL COMMENT 'Số Penalty kèo trên',
  BelowPenalty tinyint DEFAULT NULL COMMENT 'Số Penalty kèo dưới',
  AboveYellowCard tinyint DEFAULT NULL COMMENT 'Số thẻ vàng kèo trên',
  AboveRedCard tinyint DEFAULT NULL COMMENT 'Số thẻ đỏ kèo trên',
  BelowYellowCard tinyint DEFAULT NULL COMMENT 'Số thẻ vàng kèo dưới',
  BelowRedCard tinyint DEFAULT NULL COMMENT 'Số thẻ đỏ kèo dưới',
  IsGoalAbove bit(1) DEFAULT NULL COMMENT 'Là kèo trên ghi bàn',
  Discription varchar(200) DEFAULT NULL COMMENT 'Mô tả bàn thắng, thẻ đỏ, thẻ vàng',
  CreatedDate datetime DEFAULT NULL COMMENT 'Ngày tạo',
  CreatedId int DEFAULT NULL COMMENT 'Người tạo',
  CreatedName varchar(60) DEFAULT NULL COMMENT 'Tên người tạo',
  ModifiedDate datetime DEFAULT NULL COMMENT 'Ngày sửa',
  ModifiedId int DEFAULT NULL COMMENT 'Người sửa',
  ModifiedName varchar(60) DEFAULT NULL COMMENT 'Tên người sửa',
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `match`
--
CREATE TABLE `match` (
  Id int NOT NULL AUTO_INCREMENT,
  TimeStart datetime DEFAULT NULL COMMENT 'Thời gian bắt đầu trận đấu',
  SeasonId int DEFAULT NULL COMMENT 'Thuộc mùa giải',
  AboveId int DEFAULT NULL COMMENT 'Kèo trên',
  AboveName varchar(200) DEFAULT NULL COMMENT 'Tên kèo trên',
  BelowId int DEFAULT NULL COMMENT 'Kèo dưới',
  BelowName varchar(200) DEFAULT NULL COMMENT 'Tên kèo dưới',
  IsAboveHost bit(1) DEFAULT NULL COMMENT 'Kèo trên là chủ nhà',
  AboveScore tinyint DEFAULT 0 COMMENT 'Tỷ số kèo trên',
  BelowScore tinyint DEFAULT 0 COMMENT 'Tỷ số kèo dưới',
  AboveScoreHalfOne tinyint DEFAULT 0 COMMENT 'Tỷ số kèo trên hiệp 1',
  BelowScoreHalfOne tinyint DEFAULT 0 COMMENT 'Tỷ số kèo dưới hiệp 1',
  AboveScoreHalfTow tinyint DEFAULT 0 COMMENT 'Tỷ số kèo trên hiệp 2',
  BelowScoreHalfTow tinyint DEFAULT 0 COMMENT 'Tỷ số kèo dưới hiệp 2',
  AboveScoreMuftOne tinyint DEFAULT 0 COMMENT 'Tỷ số kèo trên hiệp phụ 1',
  BelowScoreMuftOne tinyint DEFAULT 0 COMMENT 'Tỷ số kèo dưới hiệp phụ 1',
  AboveScoreMuftTow tinyint DEFAULT 0 COMMENT 'Tỷ số kèo trên hiệp phụ 2',
  BelowScoreMuftTow tinyint DEFAULT 0 COMMENT 'Tỷ số kèo dưới hiệp phụ 2',
  AboveScoreShootout tinyint DEFAULT 0 COMMENT 'Tỷ số luân lưu kèo trên',
  BelowScoreShootout tinyint DEFAULT 0 COMMENT 'Tỷ số luân lưu kèo dưới',
  AboveCorner tinyint DEFAULT 0 COMMENT 'Số phạt góc kèo trên',
  BelowCorner tinyint DEFAULT 0 COMMENT 'Số phạt góc kèo dưới',
  AbovePenalty tinyint DEFAULT 0 COMMENT 'Số Penalty kèo trên',
  BelowPenalty tinyint DEFAULT 0 COMMENT 'Số Penalty kèo dưới',
  AboveYellowCard tinyint DEFAULT 0 COMMENT 'Số thẻ vàng kèo trên',
  AboveRedCard tinyint DEFAULT 0 COMMENT 'Số thẻ đỏ kèo trên',
  BelowYellowCard tinyint DEFAULT 0 COMMENT 'Số thẻ vàng kèo dưới',
  BelowRedCard tinyint DEFAULT 0 COMMENT 'Số thẻ đỏ kèo dưới',
  AboveRound tinyint DEFAULT 0 COMMENT 'Vòng đấu kèo trên',
  BelowRound tinyint DEFAULT 0 COMMENT 'Vòng đấu kèo dưới',
  isWin bit(1) DEFAULT NULL COMMENT 'tên loại đã thắng: 1, above: 0, null:draw',
  isWinOneHalf bit(1) DEFAULT NULL COMMENT 'tên loại đã thắng hiệp 1 : 1, above: 0, null:draw',
  IdDelete bit(1) DEFAULT NULL COMMENT 'Đã xóa',
  CreatedDate datetime DEFAULT NULL COMMENT 'Ngày tạo',
  CreatedId int DEFAULT NULL COMMENT 'Người tạo',
  CreatedName varchar(60) DEFAULT NULL COMMENT 'Tên người tạo',
  ModifiedDate datetime DEFAULT NULL COMMENT 'Ngày sửa',
  ModifiedId int DEFAULT NULL COMMENT 'Người sửa',
  ModifiedName varchar(60) DEFAULT NULL COMMENT 'Tên người sửa',
  IndexAboveNeedWin float(21, 20) DEFAULT 1.00000000000000000000 COMMENT 'Chỉ số kèo trên muốn thắng',
  IndexBelowNeedWin float(21, 20) DEFAULT 1.00000000000000000000 COMMENT 'Chỉ số kèo trên muốn thắng',
  IndexAboveSquadWeight float(21, 20) DEFAULT 1.00000000000000000000 COMMENT 'Chỉ số đội hình kèo trên mạnh nhất',
  IndexBelowSquadWeight float(21, 20) DEFAULT 1.00000000000000000000 COMMENT 'Chỉ số đội hình kèo dưới mạnh nhất',
  IndexAbovePerformance float(21, 20) DEFAULT 1.00000000000000000000 COMMENT 'Phong độ đội bóng kèo trên',
  IndexBelowPerformance float(21, 20) DEFAULT 1.00000000000000000000 COMMENT 'Phong độ đội bóng kèo dưới',
  IndexAboveInternalmatter float(21, 20) DEFAULT 0.00000000000000000000 COMMENT 'Vấn đề nội bộ đội bóng kèo trên',
  IndexBelowInternalmatter float(21, 20) DEFAULT 0.00000000000000000000 COMMENT 'Vấn đề nội bộ đội bóng kèo dưới',
  IndexAboveTransfer float(21, 20) DEFAULT 0.00000000000000000000 COMMENT 'Vấn đề chuyển nhượng đội bóng kèo trên',
  IndexBelowTransfer float(21, 20) DEFAULT 0.00000000000000000000 COMMENT 'Vấn đề chuyển nhượng đội bóng kèo dưới',
  IndexAboveStabilization float(21, 20) DEFAULT 1.00000000000000000000 COMMENT 'Tính ổn định của đội bóng kèo trên',
  IndexBelowStabilization float(21, 20) DEFAULT 1.00000000000000000000 COMMENT 'Tính ổn định của đội bóng kèo dưới',
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `history`
--
CREATE TABLE history (
  Id int NOT NULL AUTO_INCREMENT,
  UserId int DEFAULT NULL COMMENT 'Của người dùng',
  TypeSource int DEFAULT NULL COMMENT 'Loại nguồn chuyển vào',
  TypeDestination int DEFAULT NULL COMMENT 'Loại đích chuyển đến',
  Money float(10, 2) DEFAULT 0.00 COMMENT 'Số tiền vào/ra',
  CreateDate int DEFAULT NULL COMMENT 'Ngày tạo',
  TransactionDate int DEFAULT NULL COMMENT 'Ngày giao dịch',
  IsRecharge bit(1) DEFAULT NULL COMMENT 'Là nạp tiền',
  IsSuccess bit(1) DEFAULT NULL COMMENT 'Là chuyển thành công',
  Note varchar(400) DEFAULT NULL COMMENT 'Ghi chú',
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `gold_time_line`
--
CREATE TABLE gold_time_line (
  Id int NOT NULL AUTO_INCREMENT,
  MatchId int DEFAULT NULL COMMENT 'Trận đấu',
  TeamId int DEFAULT NULL COMMENT 'Đội bóng',
  TeamName int DEFAULT NULL COMMENT 'Tên đội bóng',
  IsGold bit(1) DEFAULT NULL COMMENT 'Là ghi bàn hay bị thủng lưới 1: ghi bàn; 2: thủng lưới',
  Timeline tinyint DEFAULT NULL COMMENT 'Thời gian ghi bàn trong trận',
  PlayerName varchar(30) DEFAULT NULL COMMENT 'Tên cầu thủ ghi bàn',
  CreatedDate datetime DEFAULT NULL COMMENT 'Ngày tạo',
  CreatedId int DEFAULT NULL COMMENT 'Người tạo',
  CreatedName varchar(60) DEFAULT NULL COMMENT 'Tên người tạo',
  ModifiedDate datetime DEFAULT NULL COMMENT 'Ngày sửa',
  ModifiedId int DEFAULT NULL COMMENT 'Người sửa',
  ModifiedName varchar(60) DEFAULT NULL COMMENT 'Tên người sửa',
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `chart`
--
CREATE TABLE chart (
  Id int NOT NULL AUTO_INCREMENT,
  Score int NOT NULL DEFAULT 0 COMMENT 'Số điểm mùa này',
  `Match` int NOT NULL DEFAULT 0 COMMENT 'Số trận đã đá',
  TeamId int DEFAULT NULL COMMENT 'Id đội bóng',
  TeamName varchar(200) DEFAULT NULL COMMENT 'Tên đội bóng',
  YellowCard int NOT NULL DEFAULT 0 COMMENT 'Số thẻ vàng của đội bóng',
  RedCard int NOT NULL DEFAULT 0 COMMENT 'Số thẻ đỏ của đội bóng',
  Corner int NOT NULL DEFAULT 0 COMMENT 'Số phạt góc được hưởng của đội bóng',
  CornerConceded int NOT NULL DEFAULT 0 COMMENT 'Số phạt góc bị của đội bóng',
  Penalty int NOT NULL DEFAULT 0 COMMENT 'Số Penalty được hưởng của đội bóng',
  PenaltyConceded int NOT NULL DEFAULT 0 COMMENT 'Số Penalty bị của đội bóng',
  Goal int NOT NULL DEFAULT 0 COMMENT 'Tổng số bàn thắng của đội bóng',
  GoalConceded int NOT NULL DEFAULT 0 COMMENT 'Tổng số bàn thua của đội bóng',
  CreatedDate datetime DEFAULT NULL COMMENT 'Ngày tạo',
  CreatedId int DEFAULT NULL COMMENT 'Người tạo',
  CreatedName varchar(60) DEFAULT NULL COMMENT 'Tên đầy đủ',
  ModifiedDate datetime DEFAULT NULL COMMENT 'Ngày sửa',
  ModifiedId int DEFAULT NULL COMMENT 'Người sửa',
  ModifiedName varchar(60) DEFAULT NULL COMMENT 'Tên người sửa',
  IsDelete bit(1) DEFAULT NULL COMMENT 'Đã xóa',
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `bet_ticket`
--
CREATE TABLE bet_ticket (
  Id int NOT NULL AUTO_INCREMENT,
  BetTicketCode varchar(30) DEFAULT NULL COMMENT 'Mã phiếu',
  HistoryId int DEFAULT NULL COMMENT 'Mã thanh toán',
  UserId int DEFAULT NULL COMMENT 'Của tài khoản',
  Timeline int DEFAULT NULL COMMENT 'Thời gian trên sân',
  BetId int DEFAULT NULL COMMENT 'Kèo thắng thua',
  SincboId varchar(200) DEFAULT NULL COMMENT 'Kèo tài xỉu',
  TypeBet varchar(200) DEFAULT NULL COMMENT 'Tên loại kèo',
  Discription varchar(400) DEFAULT NULL COMMENT 'Mô tả sự kiện',
  CreateDate datetime DEFAULT NULL COMMENT 'Ngày tạo',
  IsWin bit(1) DEFAULT NULL COMMENT 'Là thắng',
  Money float(10, 2) DEFAULT 0.00 COMMENT 'Số tiền cược',
  Profit float(4, 2) DEFAULT NULL COMMENT 'Tỷ số ăn',
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `bet_real_time`
--
CREATE TABLE bet_real_time (
  Id int NOT NULL AUTO_INCREMENT,
  TimeReal tinyint DEFAULT NULL COMMENT 'thời gian trên sân',
  MatchId int DEFAULT NULL COMMENT 'fk: thuộc trận đấu',
  AboveId int DEFAULT NULL COMMENT 'idkèo trên',
  AboveName varchar(200) DEFAULT NULL COMMENT 'kèo trên',
  BelowId int DEFAULT NULL COMMENT 'kèo dưới',
  BelowName varchar(200) DEFAULT NULL COMMENT 'Tên kèo dưới',
  IsAboveHost bit(1) DEFAULT NULL COMMENT 'kèo trên là chủ nhà',
  AboveScore tinyint DEFAULT NULL COMMENT 'Tỷ số kèo trên',
  BelowScore tinyint DEFAULT NULL COMMENT 'Tỷ số kèo dưới',
  AboveCorner tinyint DEFAULT NULL COMMENT 'số phạt góc kèo trên',
  BelowCorner tinyint DEFAULT NULL COMMENT 'số phạt góc kèo dưới',
  AbovePenalty tinyint DEFAULT NULL COMMENT 'số Penalty kèo trên',
  BelowPenalty tinyint DEFAULT NULL COMMENT 'số Penalty kèo dưới',
  AboveYellowCard tinyint DEFAULT NULL COMMENT 'số thẻ vàng kèo trên',
  AboveRedCard tinyint DEFAULT NULL COMMENT 'số thẻ đỏ kèo trên',
  BelowYellowCard tinyint DEFAULT NULL COMMENT 'số thẻ vàng kèo dưới',
  BelowRedCard tinyint DEFAULT NULL COMMENT 'số thẻ đỏ kèo dưới',
  AboveWinRatio float(4, 2) DEFAULT NULL COMMENT 'tỉ giá kèo trên thắng',
  BelowWinRatio float(4, 2) DEFAULT NULL COMMENT 'tỉ giá kèo dưới thắng',
  DrawRatio float(4, 2) DEFAULT NULL COMMENT 'tỉ giá tỷ số hòa',
  IsWin bit(1) DEFAULT NULL COMMENT 'tên loại đã thắng: 1, above: 0, null:draw',
  CreatedDate datetime DEFAULT NULL COMMENT 'Ngày tạo',
  CreatedId int DEFAULT NULL COMMENT 'Người tạo',
  CreatedName varchar(60) DEFAULT NULL COMMENT 'Tên người tạo',
  ModifiedDate datetime DEFAULT NULL COMMENT 'Ngày sửa',
  ModifiedId int DEFAULT NULL COMMENT 'Người sửa',
  ModifiedName varchar(60) DEFAULT NULL COMMENT 'Tên người sửa',
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `bet`
--
CREATE TABLE bet (
  Id int NOT NULL AUTO_INCREMENT,
  MatchTimeLineId int DEFAULT NULL COMMENT 'fk: thuộc trận đấu theo thời gian',
  AboveWinRatio float(4, 2) DEFAULT NULL COMMENT 'Tỉ giá kèo trên thắng',
  BelowWinRatio float(4, 2) DEFAULT NULL COMMENT 'Tỉ giá kèo dưới thắng',
  DrawRatio float(4, 2) DEFAULT NULL COMMENT 'Tỉ giá tỷ số hòa',
  isWin bit(1) DEFAULT NULL COMMENT 'tên loại đã thắng: 1, above: 0, null:draw',
  CreatedDate datetime DEFAULT NULL COMMENT 'Ngày tạo',
  CreatedId int DEFAULT NULL COMMENT 'Người tạo',
  CreatedName varchar(60) DEFAULT NULL COMMENT 'Tên người tạo',
  ModifiedDate datetime DEFAULT NULL COMMENT 'Ngày sửa',
  ModifiedId int DEFAULT NULL COMMENT 'Người sửa',
  ModifiedName varchar(60) DEFAULT NULL COMMENT 'Tên người sửa',
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

-- 
-- Dumping data for table user
--
INSERT INTO user VALUES
(1, 'Vũ Minh Hiếu', 'Vũ Minh', 'Hiếu', 'vmhieu', '123456', 'E10ADC3949BA59ABBE56E057F20F883E', '0369520662', 'chiminhtoi0112@gmail.com', NULL, NULL, NULL, NULL, 0.00, '2022-07-04 00:16:57', NULL, 'admin', '2022-07-04 00:16:57', NULL, 'admin', True, False);

-- 
-- Dumping data for table tournament
--
-- Table betdata.tournament does not contain any data (it is empty)

-- 
-- Dumping data for table team
--
-- Table betdata.team does not contain any data (it is empty)

-- 
-- Dumping data for table sicbo_real_time
--
-- Table betdata.sicbo_real_time does not contain any data (it is empty)

-- 
-- Dumping data for table sicbo
--
-- Table betdata.sicbo does not contain any data (it is empty)

-- 
-- Dumping data for table season
--
-- Table betdata.season does not contain any data (it is empty)

-- 
-- Dumping data for table role_user
--
-- Table betdata.role_user does not contain any data (it is empty)

-- 
-- Dumping data for table role
--
-- Table betdata.role does not contain any data (it is empty)

-- 
-- Dumping data for table reference
--
-- Table betdata.reference does not contain any data (it is empty)

-- 
-- Dumping data for table permission
--
-- Table betdata.permission does not contain any data (it is empty)

-- 
-- Dumping data for table match_time_line
--
-- Table betdata.match_time_line does not contain any data (it is empty)

-- 
-- Dumping data for table `match`
--
-- Table betdata.`match` does not contain any data (it is empty)

-- 
-- Dumping data for table history
--
-- Table betdata.history does not contain any data (it is empty)

-- 
-- Dumping data for table gold_time_line
--
-- Table betdata.gold_time_line does not contain any data (it is empty)

-- 
-- Dumping data for table chart
--
-- Table betdata.chart does not contain any data (it is empty)

-- 
-- Dumping data for table bet_ticket
--
-- Table betdata.bet_ticket does not contain any data (it is empty)

-- 
-- Dumping data for table bet_real_time
--
-- Table betdata.bet_real_time does not contain any data (it is empty)

-- 
-- Dumping data for table bet
--
-- Table betdata.bet does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;